# Custom vars
# -------------------------

current_version:  1.0.0
name: Symentis Labs

# Main Logo
# -------------------------

logo_regular: "media/logo/symentis-logo_white.png"
logo_small_devices: "media/logo/symentis-logo_sm_white.png"


# Main Navigation Links
# -------------------------

navbar_links:
  - title: "Warsztaty"
    url: "#workshops"
  - title: "Prowadzący"
    url: "#trainers"
  - title: "FAQ"
    url: "#faq"
  - title: "Kontakt"
    url: "#contact"
  - title: "Rejestracja"
    url: "#register"

# Navigation Background Color.
# Options: caribbean-green, summer-sky, golden-poppy, deep-carmine-pink
navbar_color: "summer-sky"

# Image header
# -------------------------

title:            "Symentis Labs"
date:             "19.09.2017. Hotel Focus Premium, Gdańsk"
tagline:      	  "Warsztaty prowadzone przez najlepiej ocenianych prelegentów 4Developers Festiwal"

# FAQ
# -------------------------

faq:
  title: Często zadawane pytania
  id: faq
  questions:
    - question: Gdzie odbywa się szkolenie?
      answer: "Warsztaty będą odbywać się w hotelu Focus Premium w Gdańsku, ul. Do Studzienki (w tym samym miejscu co konferencja 4Developers)"
    - question: Czy cena zawiera lunch?
      answer: Cena zawiera przerwy kawowe przez cały czas trwania szkolenia. Na lunch idziemy we własnym zakresie. <br /> Gdańsk Wrzeszcz to mekka <i>hipsterstwa</i> dając nam do wyboru masę świetnych miejsc z wysokiej jakości jedzeniem. Więc po co kisić się w hotelu.
    - question: A co z parkingiem?
      answer: Cena nie zawiera parkingu. Przy hotelu jest parking (zewnętrzny) - w cenie od 13 zł za dzień
    - question: Czy otrzymam fakturę VAT?
      answer: "Tak, fakturę otrzymasz po szkoleniu. Jeżeli potrzebujesz faktury proforma, napisz na adres: <a href=\"mailto:labs@symentis.pl\">labs@symentis.pl</a>"
    - question: Czy możliwa jest rezygnacja z uczestnictwa?
      answer: Niestety nie, opłaty nie podlegają zwrotowi. Ale nic nie stoi na przeszkodzie, aby zamiast Ciebie pojawił się ktoś inny.



# Blockquote
# -------------------------

blockquote:
   text: "Symentis to butik szkoleniowy - zespół profesjonalistów z wieloletnim, praktycznym doświadczeniem w branży rozwoju oprogramowania. Szkolenia i usługi konsultacyjne dopasowujemy do realnych potrzeb firmy, dla której pracujemy."
   tagline: "Pragmatyzm. Doświadczenie. Pasja"
   button_text: "Więcej o warsztatach"
   button_url: "#workshops"

# Services
# -------------------------

workshops:
  title: Warsztaty
  id: workshops
  lead: "Macie trochę czasu do dyspozycji po <b>4Developers Gdańsk</b>?<br />
  Jesteście gotowi pochłonąć każdą ilość praktycznych informacji? <br />
  Zapraszamy na warsztaty, które poprowadzą najlepiej ocenieni prelegenci głównej edycji 4Developers <br />
  - Jarek Pałka, Wiktor Sztajerowski i Jakub Marchwicki!"
  lead-4dev: "<b>4Developers Gdańsk</b> to nadmorska edycja największego Festiwalu Technologicznego w Polsce. Na scenie lokalnego spotkania eksperci będą dzielić się wiedzą z zakresu Soft Skills, .NET, C++ i Architektur Aplikacji. Więcej informacji o samej konferencji znajdziecie na: <a href=\"https://gdansk.4developers.org.pl\" target=_blank>https://gdansk.4developers.org.pl</a>"
  elements:
   - title: "Łagodnie, acz szczerze o świecie mikroserwisów"
     icon: "sitemap"
     description: "Słowo mikroserwisy padło w tym roku na konferencjach i portalach branżowych w liczbie, która powinna znaleźć się w Księdze Guinessa. Czy ten nowy, eksplodujący na naszych oczach trend, zmienia na zawsze naszą branżę, czy też przeminie jak wiele innych rozwiązań z kategorii 'silver bullet'? Postaramy się podczas tego szkolenia odpowiedzieć na wiele pytań, wprowadzić podstawowe wzorce i przedstawić techniki projektowania mikrousług. Podzielimy się z Wami naszym doświadczeniami i obserwacjami z implementacji mikrousług i przestrzec przed czającymi się niebezpieczeństwami, a przede wszystkim wywołać dyskusję, która pozwoli odnaleźć Wam Waszą własną drogę w tej nowej architekturze."
     youtube: amkHBU0subM
     benefits:
       - "Zaznajomisz się z wyzwaniami, które kryje za sobą podróż Twojej organizacji w głąb architektury opartej o mikrousługi; z pojawiającymi się problemami oraz wzorcami, które próbują adresować te problemy"
       - "Praktycznie poznasz przykładowe implementacje kluczowych elementów architektury mikrousług, takich jak API gatway, Service discovery lub Load-balancing"
       - "Poznasz dobre praktyki zarządzania logami, bezpieczeństwem aplikacji czy też monitorowaniem systemów w architekturze mikrousług"
       - "Będziesz miał okazję skonfrontować swoje wątpliwości z innymi uczestnikami, przedyskutować problemy z ekspertami Symentis"
   - title: "Wprowadzenie do MongoDB dla programistów"
     icon: "database"
     youtube: 5MMZDa_Y8kY
     description: "Celem szkolenia jest przybliżenie Wam tematu NoSQL na przykładzie MongoDB. Na szkoleniu dowiecie się m.in. czym jest MongoDB, jak wygląda interfejs użytkownika czy jak się ma składnia zapytań MongoDB do klasycznego SQL’a. Dowiecie się również czym jest _id i dlaczego identyfikator encji nie zawsze musi być losową wartością. Po szkoleniu będziecie potrafili zarządzać dokumentami w MongoDB (dodawać, modyfikować, pobierać), poznacie i będziecie umieli wykorzystać składnie zapytań wraz z użyciem projekcji. Oprócz tego,będzie potrafili tworzyć indeksy i wykorzystywać je w zapytaniach."

# Trainers
# -------------------------

trainers:
  title: Prowadzący
  id: trainers
  elements:
   - title: "Jarek Pałka"
     description: "Od ponad 20 lat w branży IT, jako administrator baz danych, programista, architekt, manager i 'inżynier od spraw katastrof'."
     bio: "Od ponad 20 lat w branży IT, jako administrator baz danych, programista,
     architekt, manager i 'inżynier od spraw katastrof'. Brałem udział w małych,
     średnich i nonsensownie dużych projektach, prowadzonych zgodnie zasadami
     'waterfall', Agile oraz przy braku jakichkolwiek metodyk, z tym samym zawsze
     skutkiem. To doprowadziło mnie do wniosku, że nieważne co robisz, tak długo,
     jak robisz to dobrze, w najprostszy z możliwych sposobów i używasz właściwych
     narzędzi, które wykonają pracę za Ciebie. W międzyczasie dałem się porwać ideą
     TDD oraz Software Craftmanship, do granic możliwości wyeksploatować tak
     piękne w swej prostocie pomysły jak REST i NoSQL, by potem porzucić je by
     zgłębić tajniki 'system thinking' i zachwycić się siłą jaką niesie z sobą
     'metafora' oraz odkryć, że rządzą nami te same prawa 'natury'.<br/>
     Niepokorny wyznawca kościoła JVM, badacz bytecode'u i JIT oraz wszelkiej maści
     parserów, interpeterów i kompilatorów. <br/>
     Od czasu do czasu można usłyszeć moje niskiej jakości żarty na temat
     architektury na konferencjach w Polsce i za granicą. W chwilach wolnych trener w http://symentis.pl
     i autor bloga na http://geekyprimitives.wordpress.com/ oraz samozwańczy dyktator
     w radach programowych konferencji JDD oraz 4Developers."
     url: "#bios"
     image: "media/img/trainer_jarek_sm.jpg"
   - title: "Wiktor Sztajerowski"
     description: "Entuzjasta NoSQL’a i orędownik wykorzystywania więcej niż jednej bazy danych w systemach w słusznych celach, dla sławy i zysku."
     bio: "Programista z ponad 5-cio letnim stażem, trener i konsultant w Symentis.pl, aspirujący mówca konferencyjny, znany między innymi z konferencji 4Developers i Confitura. Obecnie Java Developer w Smart Coders, entuzjasta NoSQL’a i orędownik wykorzystywania więcej niż jednej bazy danych w systemach w słusznych celach, dla sławy i zysku. Prywatnie jeden z liderów łódzkiego JUG’a oraz Zwinnej Łodzi, grupy pasjonatów metody „agile”, a także współinicjator spotkań Software Architecture & Design Debate, platformy nowego, ciekawego i szerszego spojrzenia na architekturę systemów IT."
     url: "#bios"
     image: "media/img/trainer_wiktor_2_sm.jpg"
   - title: "Jakub Marchwicki"
     description: "Programista od kilkunastu lat, architekt od kilku, czasami analityk, gdy potrzeba – konsultant, manager z wyboru, trener z zamiłowania."
     bio: "Programista od kilkunastu lat, architekt od kilku, analityk czasami, konsultant jak trzeba, manager z wyboru, trener z zamiłowania, wannabe entrepreneur - z marzeń, lider Java User Group w Gdańsku - jest spora szansa, że nic z tego nie robię dobrze. Ale próbuję... i wyciągam wnioski z porażek."
     url: "#bios"
     image: "media/img/trainer_jakub_2_sm.jpg"

# Register
# -------------------------

register:
  id: register
  title: "Rejestracja"
  tagline: "Gdańsk, <strong>19.09.2017</strong>. Hotel Focus Premium, ul. Nad Stawem 5"
  evenea_title: symentis-labs-gdansk2017

# Features Thumbs
# -------------------------

features:
  title: "Symentis to:"
  id: "about"
  read-more: "Po więcej informacji sięgnij na "
  read-more-url: http://symentis.pl
  elements:
    - title: "Szkolenia"
      icon: "users"
      description: "Szkolenia na miarę, przez praktyków dla praktyków.<br /><br /><br /><br />"
    - title: "Doradztwo"
      icon: "comments-o"
      description: "Doradzamy zarówno w kwestiach architektury, procesu wytwarzania oprogramowania jak i skalowania Twojej organizacji.<br /><br />"
    - title: "Audyt"
      icon: "search"
      description: "Audyty architektury i kodu źródłowego, realizowalności projektów. Odpowiadamy na wiele trudnych pytań.<br /><br />"
    - title: "Architecture Kata"
      icon: "cogs"
      description: "Jedyny warsztat, który łączy aspekty techniczne, techniki miękkie i komunikację w zespole. Poprzez ciągłe doskonalenie osiągniesz swoje cele."


# Contact
# -------------------------

contact:
   title: Kontakt
   id: contact
   latitude: "54.383439"
   longitude: "18.6046961"
   marker_title: "Hotel Focus Premium"
   marker_address: "Nad Stawem 5, Gdańsk"
   phone_number: "+48 607 183 320 (Jakub)"
   email_address: "labs@symentis.pl"
   disclaimer: "<p>Organizatorem szkoleń jest: Jarek Pałka (Symentis) oraz Jakub Marchwicki (42 Patterns)</p><p>Autorem zdjęcia Gdańska jest <a href=\"https://www.flickr.com/photos/kishjar/\">kishjar</a>"

# Configuration
# -------------------------

analytics:
  account: UA-104348343-1

# Dependencies
pygments: 		  false

# Permalinks
permalink: 		  none

# Server
#destination: 	  ../dist
exclude: 		  [".gitignore", "Rakefile", "Gemfile", "Gruntfile.js", "node_modules", "package.json", "README.md"]
port: 			  1984
