= 4Developers Labs by Symentis

Jedniodniowe warsztaty z trenerami link:http://symentis.pl/[Symentis Labs] dla *programistów*, *architektów*. 

== Kiedy

19 września 2017 (wtorek - po konferencji 4Developers) w Hotelu Focus Premium w Gdańsku (w tym samym miejscu do konferencja). 

== Warsztaty

=== Łagodne, acz szczere wprowadzenie do mikroserwisów

=== MongoDB dla programistów

Celem szkolenia jest przybliżenie uczestnikom tematu NoSQL na przykładzie MongoDB. 
Na szkoleniu uczestnicy dowiedzą się m.in. czym jest MongoDB, jak wygląda interfejs użytkownika czy 
jak się ma składnia zapytań MongoDB do klasycznego SQL’a. Dowiedzą się również czym jest _id i dlaczego 
identyfikator encji nie zawsze musi być losową wartością. Po szkoleniu uczestnik będzie potrafił 
zarządzać dokumentami w MongoDB (dodawać, modyfikować, pobierać), pozna i będzie umiał wykorzystać 
składnie zapytań wraz z użyciem projekcji. Oprócz tego, uczestnik będzie potrafił tworzyć indeksy 
i wykorzystywać je w zapytaniach. Dodatkowo, w ramach możliwości czasowych, uczestnik dowie się 
jak realizowana jest agregacja, jakie są jej ograniczenia, będzie potrafił filtrować i agregować 
dane z dokumentów oraz pozna mechanizm replikacji danych.

== Trenerzy

=== Jarosław Pałka

Od ponad 10 lat w branży IT, jako administrator baz danych, programista, architekt, manager 
i "inżynier od spraw katastrof". Brał udział w małych, średnich i nonsensownie dużych projektach, 
prowadzonych zgodnie zasadami "waterfall", Agile oraz przy braku jakichkolwiek metodyk, zawsze z tym samym skutkiem. 
Co doprowadziło go do wniosku, że nie ważne co robisz tak długo, jak robisz to dobrze, w najprostszy z możliwych sposobów 
i używasz właściwych narzędzi które wykonają pracę za Ciebie. 

W międzyczasie dał się porwać ideą TDD oraz Software Craftmanship, do granic możliwości wyeksploatować tak piękne w swej 
prostocie pomysły jak REST, JavaScript i NOSQL, by potem porzucić je by zgłębić tajniki "system thinking" i 
zachwycić się siłą jaką niesie z sobą "metafora" i odkryć, że rządzą nami te same prawa "natury".  

=== Wiktor Sztajerowski

Programista z przypadku, Java Dev z zamiłowania, entuzjasta NoSQL. Wyznaje zasadę "keep it simple stupid" i 
mocno wierzy w sens inwestowania w jakość kodu oraz "agile" przez małe "a". 
Na codzień programista w BMS | Bankruptcy Management Solutions, 
po godzinach jeden z liderów łódzkiego JUGa oraz Zwinnej Łodzi - społeczności około-agilowej. 

=== Jakub Marchwicki

Jakub Marchwicki - programista od kilkunastu lat, architekt od kilku, czasami analityk, gdy potrzeba – 
konsultant, manager z wyboru, trener z zamiłowania, wannabe entrepreneur z marzeń, lider JUG w Gdańsku. 
Z oprogramowaniem związany przez całe życie zawodowe. Przez ostatnie lata realizował ambicje managerskie, 
m.in. jako dyrektor techniczny w 250 osobowej firmie. Uważa, że najlepszym sposobem pracy ze specjalistami 
jest aktywne dzielenie się własną wiedzą oraz aktywnie słuchać innych. Przekazuje doświadczenie w formie 
wykładów, wystąpień na konferencjach oraz szkoleń.
